const $=id=>document.getElementById(id);
    const normalize=value=>String(value||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’‘]/g,"'").trim();
    const profileSlug=value=>String(value||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\x00-\x7F]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"artist";
    const GENRES={
      "hip-hop":{label:"Hip-Hop",terms:["hip-hop","hip hop","rapper"," rap ","rap.","rap,","boom bap","trap","drill","emcee"]},
      "rnb-soul":{label:"R&B / Soul",terms:["r&b","rnb","rhythm and blues","neo-soul","neo soul","soul","soulful"]},
      "pop":{label:"Pop",terms:[" pop ","synth-pop","synthpop","dance-pop","art-pop","electropop","dream pop","indie-pop","indie pop","scandi-pop"]},
      "rock":{label:"Rock",terms:[" rock ","garage rock","hard rock","classic rock","post-rock","rockabilly"]},
      "indie-alternative":{label:"Indie / Alternative",terms:["indie","alternative","alt-","shoegaze","post-punk","new wave","dream pop","art rock","experimental"]},
      "electronic-dance":{label:"Electronic / Dance",terms:["electronic","electronica","house","techno"," dance ","club","edm","ambient","trip-hop","trip hop","downtempo","synth"]},
      "folk-songwriter":{label:"Folk / Singer-Songwriter",terms:["folk","singer-songwriter","singer songwriter","acoustic","roots music"]},
      "country-americana":{label:"Country / Americana",terms:["country","americana","alt-country","bluegrass","honky tonk"]},
      "jazz":{label:"Jazz",terms:["jazz","bebop","improvisation","improvised music"]},
      "punk-hardcore":{label:"Punk / Hardcore",terms:["punk","hardcore","post-hardcore","emo","ska punk"]},
      "metal":{label:"Metal",terms:["metal","doom","black metal","death metal","thrash","sludge","metalcore"]},
      "reggae-dancehall":{label:"Reggae / Dancehall",terms:["reggae","dancehall","dub","soca","caribbean"]}
    };
    const ERA_LABELS={"2020s":"2020s","2010s":"2010s","2000s":"2000s","1990s":"1990s","pre-1990":"1980s and earlier"};
    const DISCOVERY_EXCLUSIONS=new Set(["ari lennox"]);
    const REFERENCE_TASTES={"vibi":["pop","indie-alternative"],"sza":["rnb-soul","pop"],"erykah badu":["rnb-soul"],"d'angelo":["rnb-soul"],"anderson .paak":["rnb-soul","hip-hop"],"kendrick lamar":["hip-hop"],"j. cole":["hip-hop"],"de la soul":["hip-hop"],"a tribe called quest":["hip-hop"],"outkast":["hip-hop"],"nas":["hip-hop"],"radiohead":["indie-alternative","rock","electronic-dance"],"portishead":["electronic-dance","indie-alternative"],"massive attack":["electronic-dance","indie-alternative"],"nirvana":["rock","indie-alternative"],"the cure":["indie-alternative","rock"],"phoebe bridgers":["indie-alternative","folk-songwriter"],"boygenius":["indie-alternative","folk-songwriter"],"taylor swift":["pop","folk-songwriter"],"beyonce":["pop","rnb-soul"],"charli xcx":["pop","electronic-dance"],"dua lipa":["pop","electronic-dance"],"daft punk":["electronic-dance"],"fred again..":["electronic-dance"]};
    let library=[],imageMap=new Map(),ready=false;
    function escapeHtml(value){const div=document.createElement("div");div.textContent=String(value||"");return div.innerHTML;}
    function escapeAttr(value){return escapeHtml(value).replace(/"/g,"&quot;");}
    function classifyGenres(text){const haystack=` ${normalize(text)} `;return Object.entries(GENRES).filter(([,genre])=>genre.terms.some(term=>haystack.includes(normalize(term)))).map(([key])=>key);}
    function inferEras(text){const value=normalize(text),eras=new Set(),years=[...value.matchAll(/\b(19[5-9]\d|20[0-2]\d)\b/g)].map(m=>Number(m[1]));years.forEach(year=>{if(year>=2020)eras.add("2020s");else if(year>=2010)eras.add("2010s");else if(year>=2000)eras.add("2000s");else if(year>=1990)eras.add("1990s");else eras.add("pre-1990");});if(/\b(current|contemporary|emerging|2020s)\b/.test(value))eras.add("2020s");if(/\b(2010s|streaming era)\b/.test(value))eras.add("2010s");if(/\b(2000s|aughts)\b/.test(value))eras.add("2000s");if(/\b(1990s|90s|nineties)\b/.test(value))eras.add("1990s");if(/\b(1980s|80s|1970s|70s|1960s|60s|legacy)\b/.test(value))eras.add("pre-1990");return[...eras];}
    function parseImages(tsv){const map=new Map();String(tsv||"").split(/\r?\n/).slice(1).forEach(line=>{const tab=line.indexOf("\t");if(tab<1)return;const name=line.slice(0,tab).trim(),url=line.slice(tab+1).trim();if(name&&url&&!map.has(normalize(name)))map.set(normalize(name),url);});return map;}
    function cleanSummaryName(summary){if(!summary)return"";const textNode=[...summary.childNodes].find(node=>node.nodeType===Node.TEXT_NODE&&node.textContent.trim());return textNode?textNode.textContent.trim():summary.textContent.replace(/\(\s*\d+\s+tracks?\s*\)\s*$/i,"").trim();}
    function parseArtistLibrary(html){const doc=new DOMParser().parseFromString(html,"text/html"),artists=[],seen=new Set();doc.querySelectorAll("details[data-search]").forEach(details=>{const name=cleanSummaryName(details.querySelector("summary")),key=normalize(name);if(!name||seen.has(key)||DISCOVERY_EXCLUSIONS.has(key))return;seen.add(key);const bio=details.querySelector(".profile-bio")?.textContent.trim()||"",location=details.querySelector(".profile-location")?.textContent.trim()||"",tracks=[...details.querySelectorAll(".track")].map(track=>({title:track.querySelector(".track-title")?.textContent.trim()||"",album:track.querySelector(".track-album")?.textContent.trim()||""})).filter(track=>track.title),requestHref=details.querySelector(".request-link")?.getAttribute("href")||`./index.html?request=${encodeURIComponent(name)}`,featureAnchor=[...details.querySelectorAll(".profile-links a")].find(a=>/northern dial feature/i.test(a.textContent)),feature=featureAnchor?.getAttribute("href")||"",existingProfile=details.querySelector("summary .artist-page-link")?.getAttribute("href")||"",profileHref=existingProfile||(bio?`./artists/${profileSlug(name)}.html`:""),signals=[bio,...tracks.slice(0,12).map(track=>track.album)].join(" ");artists.push({name,key,bio,location,tracks,requestHref,feature,profileHref,genres:classifyGenres(signals),eras:inferEras(signals),image:imageMap.get(key)||""});});return artists;}
    function populateSuggestions(){const names=[...library.map(a=>a.name),...Object.keys(REFERENCE_TASTES)],unique=[...new Set(names)].sort((a,b)=>a.localeCompare(b));$("artistSuggestions").innerHTML=unique.map(name=>`<option value="${escapeAttr(name)}"></option>`).join("");}
    function resolveTaste(input){const raw=String(input||"").trim(),key=normalize(raw);if(!key)return{genres:[],source:"",matched:false,excludedKey:""};const exact=library.find(artist=>artist.key===key);if(exact&&exact.genres.length)return{genres:exact.genres,source:exact.name,matched:true,excludedKey:exact.key};const close=library.find(artist=>artist.key.includes(key)||key.includes(artist.key));if(close&&close.genres.length)return{genres:close.genres,source:close.name,matched:true,excludedKey:close.key};if(REFERENCE_TASTES[key])return{genres:REFERENCE_TASTES[key],source:raw,matched:true,excludedKey:key};return{genres:[],source:"",matched:false,excludedKey:""};}
    function scoreArtist(artist,genre,era,tasteGenres){let score=Math.random()*1.2;if(genre&&artist.genres.includes(genre))score+=12;score+=artist.genres.filter(g=>tasteGenres.includes(g)).length*7;if(era&&artist.eras.includes(era))score+=5;if(artist.bio)score+=1;if(artist.feature)score+=1;if(artist.tracks.length)score+=.5;return score;}
    function makeRecommendations({surprise=false}={}){if(!ready)return;let genre=$("genreSelect").value,era=$("eraSelect").value,tasteInput=$("tasteInput").value.trim();if(surprise){genre="";era="";tasteInput="";$("genreSelect").value="";$("eraSelect").value="";$("tasteInput").value="";}const taste=resolveTaste(tasteInput);if(tasteInput&&!taste.matched&&!genre&&!era){showStatus(`I don’t have enough information about “${tasteInput}” yet. Pick a genre or era, or choose an artist from the suggestions.`);$("resultsSection").classList.remove("show");return;}if(tasteInput&&!taste.matched)showStatus(`I don’t have a reliable taste profile for “${tasteInput}” yet, so these picks use only your selected genre and era.`);else hideStatus();let candidates=library.filter(a=>a.key!==taste.excludedKey);if(genre){const strict=candidates.filter(a=>a.genres.includes(genre));if(strict.length>=5)candidates=strict;}else if(taste.genres.length){const strict=candidates.filter(a=>a.genres.some(g=>taste.genres.includes(g)));if(strict.length>=5)candidates=strict;}const ranked=candidates.map(artist=>({artist,score:scoreArtist(artist,genre,era,taste.genres)})).sort((a,b)=>b.score-a.score),pool=ranked.slice(0,Math.min(12,ranked.length)),picks=[];while(pool.length&&picks.length<5){const weightedTop=Math.min(6,pool.length),index=Math.floor(Math.random()*weightedTop);picks.push(pool.splice(index,1)[0].artist);}renderResults(picks,genre,era,taste,surprise);}
    function whyLine(artist,genre,era,taste){const reasons=[];if(genre&&artist.genres.includes(genre))reasons.push(`${GENRES[genre].label} fit`);const overlap=artist.genres.find(g=>taste.genres.includes(g));if(overlap&&taste.source)reasons.push(`shares a ${GENRES[overlap].label.toLowerCase()} lane with ${taste.source}`);if(era&&artist.eras.includes(era))reasons.push(`${ERA_LABELS[era]} signal`);if(!reasons.length&&artist.genres.length)reasons.push(`${GENRES[artist.genres[0]].label} from the Northern Dial library`);return reasons.length?reasons.join(" · "):"Canadian artist from the Northern Dial library";}
    function truncate(text,len=170){const value=String(text||"").trim();if(value.length<=len)return value;return value.slice(0,len).replace(/\s+\S*$/,"")+"…";}
    function renderResults(picks,genre,era,taste,surprise){const summary=[];if(genre)summary.push(GENRES[genre].label);if(era)summary.push(ERA_LABELS[era]);if(taste.matched&&taste.source)summary.push(`fans of ${taste.source}`);$("resultsSummary").textContent=surprise?"Five picks from Northern Dial’s Canadian artist library.":summary.length?`Matched around ${summary.join(" · ")}.`:"Five picks from Northern Dial’s Canadian artist library.";$("resultsGrid").innerHTML=picks.map((artist,index)=>{const requestUrl=artist.requestHref||`./index.html?request=${encodeURIComponent(artist.name)}`,profileUrl=artist.profileHref||"",primaryUrl=profileUrl||artist.feature||requestUrl,tags=[...artist.genres.slice(0,3).map(g=>GENRES[g]?.label).filter(Boolean),...artist.eras.slice(0,1).map(e=>ERA_LABELS[e]).filter(Boolean)],image=artist.image?`<img class="artist-image" src="${escapeAttr(artist.image)}" alt="${escapeAttr(artist.name)}" loading="lazy" decoding="async" onerror="this.outerHTML='<div class=&quot;image-fallback&quot;>ND</div>'">`:`<div class="image-fallback">ND</div>`,track=artist.tracks[0],profile=profileUrl?`<a class="feature-link" href="${escapeAttr(profileUrl)}">Artist Profile</a>`:"",feature=artist.feature?`<a class="feature-link" href="${escapeAttr(artist.feature)}">Read Feature</a>`:"",bio=artist.bio||"Explore this Canadian artist in the Northern Dial catalogue.";return`<article class="artist-card"><div class="card-top"><a class="artist-image-link" href="${escapeAttr(primaryUrl)}" aria-label="${escapeAttr(artist.feature?`Read about ${artist.name}`:`Request ${artist.name}`)}">${image}<span class="rank">Pick ${index+1}</span></a><div><h3 class="artist-name"><a href="${escapeAttr(primaryUrl)}">${escapeHtml(artist.name)}</a></h3><div class="location">${escapeHtml(artist.location||"Canada")}</div><div class="tags">${tags.map(tag=>`<span class="tag">${escapeHtml(tag)}</span>`).join("")}</div><p class="why">${escapeHtml(whyLine(artist,genre,era,taste))}</p></div></div><div class="card-lower"><p class="bio">${escapeHtml(truncate(bio))}</p>${track?`<div class="start-track"><strong>On Northern Dial:</strong> ${escapeHtml(track.title)}</div>`:""}<div class="card-actions"><a class="request-link" href="${escapeAttr(requestUrl)}">Request ${escapeHtml(artist.name)}</a>${profile}${feature}</div></div></article>`;}).join("");$("resultsSection").classList.add("show");$("resultsSection").scrollIntoView({behavior:"smooth",block:"start"});}
    function showStatus(message){$("status").textContent=message;$("status").classList.add("show");}
    function hideStatus(){$("status").textContent="";$("status").classList.remove("show");}
    async function loadDiscoveryData(){try{const[artistsResponse,imagesResponse]=await Promise.all([fetch("./artists.html"),fetch("./library_artist_images.tsv")]);if(!artistsResponse.ok)throw new Error(`Artist library returned ${artistsResponse.status}`);const[artistsHtml,imagesTsv]=await Promise.all([artistsResponse.text(),imagesResponse.ok?imagesResponse.text():Promise.resolve("")]);imageMap=parseImages(imagesTsv);library=parseArtistLibrary(artistsHtml);if(library.length<5)throw new Error("Not enough artist records");populateSuggestions();ready=true;$("discoverBtn").disabled=false;$("discoverBtn").textContent="Find Me 5 Artists";$("surpriseBtn").disabled=false;const tagged=library.filter(a=>a.genres.length).length;showStatus(`${library.length.toLocaleString()} Canadian artist profiles loaded. ${tagged.toLocaleString()} currently have discovery genre signals.`);setTimeout(hideStatus,3500);}catch(error){console.error("Discovery load failed:",error);$("discoverBtn").textContent="Discovery unavailable";showStatus("The artist library couldn’t load right now. Try again shortly or browse the full artist index.");}}
    $("discoverBtn").addEventListener("click",()=>makeRecommendations());
    $("surpriseBtn").addEventListener("click",()=>makeRecommendations({surprise:true}));
    $("tasteInput").addEventListener("keydown",event=>{if(event.key==="Enter"&&ready)makeRecommendations();});
    loadDiscoveryData();
